theme: minima

title: That's my new site!
author: Elena Zelenaya
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  That is my new site to practice in usage of GitHub Pages and Jekyll. It's awesome!

# social links
telegram_username: zlnln # DO NOT include the @ character, or else the build will fail!
github_username:  lenazelenaya # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
